// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcsPZrK7sMGDegqgBzQTFgU2GiF8vQfn8',
    appId: '1:505948726540:web:d1ace9940a541219025529',
    messagingSenderId: '505948726540',
    projectId: 'csci-4100u-final-pg-friendlist',
    authDomain: 'csci-4100u-final-pg-friendlist.firebaseapp.com',
    storageBucket: 'csci-4100u-final-pg-friendlist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgrBlQbi55hH1ejD7w5dA6N42R3Shmso',
    appId: '1:505948726540:android:10ddf9ed522639a8025529',
    messagingSenderId: '505948726540',
    projectId: 'csci-4100u-final-pg-friendlist',
    storageBucket: 'csci-4100u-final-pg-friendlist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8VRJG1QHx1ILBbp7GDnrbqtfPyz0EOxQ',
    appId: '1:505948726540:ios:f7ff2130fc2aebff025529',
    messagingSenderId: '505948726540',
    projectId: 'csci-4100u-final-pg-friendlist',
    storageBucket: 'csci-4100u-final-pg-friendlist.appspot.com',
    iosBundleId: 'com.example.studentHelperProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8VRJG1QHx1ILBbp7GDnrbqtfPyz0EOxQ',
    appId: '1:505948726540:ios:07123219d75fbcbf025529',
    messagingSenderId: '505948726540',
    projectId: 'csci-4100u-final-pg-friendlist',
    storageBucket: 'csci-4100u-final-pg-friendlist.appspot.com',
    iosBundleId: 'com.example.studentHelperProject.RunnerTests',
  );
}
