import 'package:cloud_firestore/cloud_firestore.dart';

// Defines a model for chat messages in the application.
class Message {
  // Unique identifier for the message, nullable for new messages to be generated by Firestore.
  final String? uid;
  // Timestamp of the message, using Firestore's Timestamp type for compatibility.
  final Timestamp timestamp;
  // Sender's display name.
  final String sender;
  // Sender's unique identifier.
  final String senderUid;
  // Receiver's display name.
  final String receiver;
  // Receiver's unique identifier.
  final String receiverUid;
  // Content of the message.
  final String content;
  // Flag to indicate if the message has been edited.
  final bool edited;
  // Flag to indicate if the message has been deleted.
  final bool deleted;
  // URL of the image or video, nullable since not all messages will include media.
  final String? mediaUrl;

  // Constructor for creating a new Message instance.
  Message({
    this.uid,
    required this.timestamp,
    required this.sender,
    required this.senderUid,
    required this.receiver,
    required this.receiverUid,
    required this.content,
    this.edited = false,
    this.deleted = false,
    this.mediaUrl,
  });

  // Converts a Message instance to a map, useful for Firestore operations.
  Map<String, dynamic> toMap() {
    return {
      'uid': uid,
      // 'timestamp': timestamp,
      'timestamp': timestamp.millisecondsSinceEpoch,
      'sender': sender,
      'senderUid': senderUid,
      'receiver': receiver,
      'receiverUid': receiverUid,
      'content': content,
      'edited': edited,
      'deleted': deleted,
      'mediaUrl': mediaUrl,
    };
  }

  // Factory constructor to create a Message instance from a map of values.
  static Message fromMap(Map<String, dynamic> map, String? documentId) {
    Timestamp timestamp = _getTimestampFromMap(map);
    bool edited = _getBoolFromInt(map['edited']);
    bool deleted = _getBoolFromInt(map['deleted']);

    return Message(
      uid: documentId,
      timestamp: timestamp,
      sender: map['sender'],
      senderUid: map['senderUid'],
      receiver: map['receiver'],
      receiverUid: map['receiverUid'],
      content: map['content'],
      edited: edited,
      deleted: deleted,
      mediaUrl: map['mediaUrl'],
    );
  }

  static Timestamp _getTimestampFromMap(Map<String, dynamic> map) {
    Timestamp timestamp;
    // Check if the 'timestamp' field is a string or an integer
    if (map['timestamp'] is String) {
      int timestampMilliseconds = int.parse(map['timestamp']);
      timestamp = Timestamp.fromMillisecondsSinceEpoch(timestampMilliseconds);
    } else if (map['timestamp'] is int) {
      timestamp = Timestamp.fromMillisecondsSinceEpoch(map['timestamp']);
    } else {
      // Handle the case where 'timestamp' is neither int nor String
      throw FormatException('Invalid format for timestamp field');
    }
    return timestamp;
  }

  static bool _getBoolFromInt(dynamic value) {
    if (value is int) {
      return value != 0;
    }
    return value ?? false;
  }

  // Creates a copy of the Message with modified fields, providing default values for unmodified fields.
  Message copyWith({
    String? uid,
    Timestamp? timestamp,
    String? sender,
    String? senderUid,
    String? receiver,
    String? receiverUid,
    String? content,
    bool? edited,
    bool? deleted,
    String? mediaUrl,
  }) {
    return Message(
      uid: uid ?? this.uid,
      timestamp: timestamp ?? this.timestamp,
      sender: sender ?? this.sender,
      senderUid: senderUid ?? this.senderUid,
      receiver: receiver ?? this.receiver,
      receiverUid: receiverUid ?? this.receiverUid,
      content: content ?? this.content,
      edited: edited ?? this.edited,
      deleted: deleted ?? this.deleted,
      mediaUrl: mediaUrl ?? this.mediaUrl,
    );
  }
}
